!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  compress_map: true
  filter_ground: false
  filter_speckles: true
  ground_filter_angle: 0.15
  ground_filter_distance: 0.04
  ground_filter_plane_distance: 0.06992999999999999
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      compress_map: true
      filter_ground: true
      filter_speckles: true
      ground_filter_angle: 0.15
      ground_filter_distance: 0.04
      ground_filter_plane_distance: 0.06992999999999999
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      incremental_2D_projection: false
      max_depth: 16
      name: Default
      occupancy_max_z: 1.5
      occupancy_min_z: 0.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pointcloud_max_z: 1.6
      pointcloud_min_z: 0.0
      sensor_model_hit: 0.7
      sensor_model_max: 0.97
      sensor_model_max_range: 8.0
      sensor_model_min: 0.2
      sensor_model_miss: 0.3
      state: true
      type: ''
    state: []
  incremental_2D_projection: false
  max_depth: 16
  occupancy_max_z: 1.5
  occupancy_min_z: 0.0
  pointcloud_max_z: 1.5
  pointcloud_min_z: 0.0
  sensor_model_hit: 0.7
  sensor_model_max: 0.97
  sensor_model_max_range: 3.5
  sensor_model_min: 0.2
  sensor_model_miss: 0.4
state: []
