version: "3.8"
services:
  trajectory_tracker:
    build:
      context: docker/ros1
      args:
        - user_id=1000
        - COLCON_WS=/root/catkin_ws/

    network_mode: host
    privileged: true

    # Enabling GPU access with Compose
    # https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
             - capabilities: [gpu]
               count: all

    environment:
      - TERM=xterm-256color
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    #gpus: all      

    volumes:
      - ./data:/root/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/input:/dev/input
      - /dev:/dev
      
    devices:
      - /dev:/dev
